/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  BasicKYCExampleDApp,
  BasicKYCExampleDAppInterface,
} from "../BasicKYCExampleDApp";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract VerificationSBT",
        name: "_SBT",
        type: "address",
      },
      {
        internalType: "contract IZkKYCVerifier",
        name: "_verifierWrapper",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "SBT",
    outputs: [
      {
        internalType: "contract VerificationSBT",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isVerified",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "a",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "b",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "c",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[]",
        name: "input",
        type: "uint256[]",
      },
    ],
    name: "registerKYC",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "verifierWrapper",
    outputs: [
      {
        internalType: "contract IZkKYCVerifier",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class BasicKYCExampleDApp__factory {
  static readonly abi = _abi;
  static createInterface(): BasicKYCExampleDAppInterface {
    return new utils.Interface(_abi) as BasicKYCExampleDAppInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BasicKYCExampleDApp {
    return new Contract(address, _abi, signerOrProvider) as BasicKYCExampleDApp;
  }
}
