/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGalacticaInstitution,
  IGalacticaInstitutionInterface,
} from "../IGalacticaInstitution";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "institutionPubKey",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGalacticaInstitution__factory {
  static readonly abi = _abi;
  static createInterface(): IGalacticaInstitutionInterface {
    return new utils.Interface(_abi) as IGalacticaInstitutionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGalacticaInstitution {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IGalacticaInstitution;
  }
}
