compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@wagmi/core@*":
    dependencies:
      "@tanstack/query-core": ">=5.0.0"
  "@walletconnect/modal-ui@*":
    dependencies:
      lit-html: "*"
  react-metamask-avatar@*:
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
      "@metamask/jazzicon": "*"
  vite-plugin-checker@*:
    dependencies:
      optionator: ^0.9.1
  eslint-plugin-perfectionist@*:
    dependencies:
      "@typescript-eslint/types": "*"
