/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AgeProofZkKYC } from "./AgeProofZkKYC";
export type { ERC20 } from "./ERC20";
export type { IGalacticaInstitution } from "./IGalacticaInstitution";
export type { IVerificationSBT } from "./IVerificationSBT";
export type { MockDApp } from "./MockDApp";
export * as factories from "./factories";
export { AgeProofZkKYC__factory } from "./factories/AgeProofZkKYC__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { IGalacticaInstitution__factory } from "./factories/IGalacticaInstitution__factory";
export { IVerificationSBT__factory } from "./factories/IVerificationSBT__factory";
export { MockDApp__factory } from "./factories/MockDApp__factory";
