/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface MockDAppInterface extends utils.Interface {
  functions: {
    "SBT()": FunctionFragment;
    "airdropToken(uint256,uint256[2],uint256[2][2],uint256[2],uint256[])": FunctionFragment;
    "hasReceivedToken1(bytes32)": FunctionFragment;
    "hasReceivedToken2(bytes32)": FunctionFragment;
    "setToken1(address)": FunctionFragment;
    "setToken2(address)": FunctionFragment;
    "token1()": FunctionFragment;
    "token1AirdropAmount()": FunctionFragment;
    "token2()": FunctionFragment;
    "token2AirdropAmount()": FunctionFragment;
    "verifierWrapper()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "SBT"
      | "airdropToken"
      | "hasReceivedToken1"
      | "hasReceivedToken2"
      | "setToken1"
      | "setToken2"
      | "token1"
      | "token1AirdropAmount"
      | "token2"
      | "token2AirdropAmount"
      | "verifierWrapper"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "SBT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "airdropToken",
    values: [
      PromiseOrValue<BigNumberish>,
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReceivedToken1",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReceivedToken2",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setToken1",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setToken2",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "token1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "token1AirdropAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "token2AirdropAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifierWrapper",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "SBT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "airdropToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReceivedToken1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReceivedToken2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setToken1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setToken2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "token1AirdropAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "token2AirdropAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifierWrapper",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MockDApp extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockDAppInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    SBT(overrides?: CallOverrides): Promise<[string]>;

    airdropToken(
      tokenIndex: PromiseOrValue<BigNumberish>,
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      input: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hasReceivedToken1(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    hasReceivedToken2(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setToken1(
      _token1: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setToken2(
      _token2: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    token1(overrides?: CallOverrides): Promise<[string]>;

    token1AirdropAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    token2(overrides?: CallOverrides): Promise<[string]>;

    token2AirdropAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    verifierWrapper(overrides?: CallOverrides): Promise<[string]>;
  };

  SBT(overrides?: CallOverrides): Promise<string>;

  airdropToken(
    tokenIndex: PromiseOrValue<BigNumberish>,
    a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    b: [
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
    ],
    c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    input: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hasReceivedToken1(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  hasReceivedToken2(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setToken1(
    _token1: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setToken2(
    _token2: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  token1(overrides?: CallOverrides): Promise<string>;

  token1AirdropAmount(overrides?: CallOverrides): Promise<BigNumber>;

  token2(overrides?: CallOverrides): Promise<string>;

  token2AirdropAmount(overrides?: CallOverrides): Promise<BigNumber>;

  verifierWrapper(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    SBT(overrides?: CallOverrides): Promise<string>;

    airdropToken(
      tokenIndex: PromiseOrValue<BigNumberish>,
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      input: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    hasReceivedToken1(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    hasReceivedToken2(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setToken1(
      _token1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setToken2(
      _token2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    token1(overrides?: CallOverrides): Promise<string>;

    token1AirdropAmount(overrides?: CallOverrides): Promise<BigNumber>;

    token2(overrides?: CallOverrides): Promise<string>;

    token2AirdropAmount(overrides?: CallOverrides): Promise<BigNumber>;

    verifierWrapper(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    SBT(overrides?: CallOverrides): Promise<BigNumber>;

    airdropToken(
      tokenIndex: PromiseOrValue<BigNumberish>,
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      input: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hasReceivedToken1(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasReceivedToken2(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setToken1(
      _token1: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setToken2(
      _token2: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    token1(overrides?: CallOverrides): Promise<BigNumber>;

    token1AirdropAmount(overrides?: CallOverrides): Promise<BigNumber>;

    token2(overrides?: CallOverrides): Promise<BigNumber>;

    token2AirdropAmount(overrides?: CallOverrides): Promise<BigNumber>;

    verifierWrapper(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    SBT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    airdropToken(
      tokenIndex: PromiseOrValue<BigNumberish>,
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      input: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hasReceivedToken1(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasReceivedToken2(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setToken1(
      _token1: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setToken2(
      _token2: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    token1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    token1AirdropAmount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    token2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    token2AirdropAmount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifierWrapper(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
